config/routes.rb
Rails.application.routes.draw do
  
  root to: "homes#top"
  devise_for :users
  
  resources :books, only: [:new, :index, :show, :edit, :create, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
    
  validates :title, presence: true
  validates :body,  presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fit: [width, height]).processed
  end
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


    private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]
  
  def new
    @newbook = Book.new
  end
  
  def create
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
    if @newbook.save
       flash[:notice] = "You have created book successfully!!"
      redirect_to book_path(@newbook)
    else
      @books = Book.all
      render :index
    end
  end
  
  def index
    @newbook = Book.new
    @books = Book.all
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully~"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private

    def book_params
      params.require(:book).permit(:title, :body)
    end
  
    def is_matching_login_user
      book = Book.find(params[:id])
      unless book.user_id == current_user.id
        redirect_to books_path
      end
    end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @newbook = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @newbook = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully~"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
  
    def is_matching_login_user
      user_id = params[:id].to_i
      unless user_id == current_user.id
       redirect_to user_path(current_user)
      end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
      
        <div id="error_explanation">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class:"btn btn-success" %>
        </div>
      <% end %>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  
  <div id="error_explanation">
    <% if @newbook.errors.any? %>
      <h3><%= @newbook.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
        <% @newbook.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_info', user: current_user, newbook: @newbook %>
    </div>
    <!-- 自分info｜ブック一覧 -->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover teble-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to  user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/user_info', user: @book.user, newbook: @newbook %>
  </div>
  <!-- :idのユーザーのinfo｜ブックの詳細(自分なら編集ボタン表示) -->
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td><%= image_tag @book.user.get_profile_image(100,100) %><br />
              <%= link_to @book.user.name, user_path(@book.user) %></td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path, class:"btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path, class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消してしまいますか？" %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  
</div>
</div>

app/views/homes/about.html.erb
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>

app/views/homes/top.html.erb
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
            <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/" ><spen>Bookers</spen></a>
        <div>
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user), class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class:"nav-link text-light" do %>
                <i class="fas fa-users"></i>Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class:"nav-link text-light" do %>
                <i class="fas fa-book-open"></i>Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>Log out
              <% end %>
            </li>

            <% else %>
            <li>
              <%= link_to root_path, class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path, class:"nav-link text-light" do %>
                <i class="fas fa-link"></i>About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>Log in
              <% end %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  
  <main>
    <p id="notice"><%= flash[:notice] %></p>
    
    <%= yield %>
    
  </main>
  
    <fotter>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </fotter>
    
  </body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>
<div class="row">
  <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %><i class="fas fa-user-cog"></i><% end %>
</div>

<h2 class="mt-3">New book</h2>
<%= form_with model: newbook do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class:"book_title form-control", id:"book_title" %>
  </div>
  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class:"book_body form-control", id:"book_body" %>
  </div>
  <div  class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
      
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        
        <div class="form-group">
         <label for="user_name">Name</label>
          <%= f.text_field :name, class:"form-control name" %>
         </div>
        
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, accept: "image/*", class:"form-control-file user_image" %>
        </div>
        
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class:"form-control introduction" %>
        </div>
        
        <div class="form-group">
          <%= f.submit 'Update User', class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', user: current_user, newbook: @newbook %>
    </div>
      <!-- 自分のinfo｜ユーザーの一覧 -->
    <div class="col-md-8 offset-md-1">
      <h2>Uses</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspen="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(80,80) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </table>
    </div>
    
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', user: @user,newbook: @newbook %>
    </div>
      <!-- ログイン後最初のページ|:idの投稿一覧 -->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover teble-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspen="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to  user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
  </div>
</div>